# Generated by Django 3.1 on 2020-09-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20200921_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulklessonrequest',
            old_name='number',
            new_name='bl_number',
        ),
        migrations.RenameField(
            model_name='bulklessonrequest',
            old_name='request_by',
            new_name='bl_request_by',
        ),
        migrations.RenameField(
            model_name='bulklessonrequest',
            old_name='request_to',
            new_name='bl_request_to',
        ),
        migrations.RenameField(
            model_name='ongoingsupportrequest',
            old_name='number',
            new_name='os_number_bk',
        ),
        migrations.RenameField(
            model_name='ongoingsupportrequest',
            old_name='request_by',
            new_name='os_request_by',
        ),
        migrations.RenameField(
            model_name='ongoingsupportrequest',
            old_name='request_to',
            new_name='os_request_to',
        ),
    ]
