# Generated by Django 3.1 on 2020-10-26 06:07

from django.db import migrations, models
import django.db.models.deletion
import restapp.models.file_handle


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20200921_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=restapp.models.file_handle.directory_path)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blogs_img', to='restapp.blogs')),
            ],
        ),
    ]
